namespace CursorPaginator.Generator.Core;

internal static class GeneratorConstants
{
    public const int DefaultStringBuilderCapacity = 1024;
    public const int LargeStringBuilderCapacity = 32768;
    public const int MaxSortableFields = 8;
    public const int MaxCursorSize = 4096; // 4KB max cursor size
    public const string GeneratedCodeComment = "// <auto-generated/>";
    public const string NullableEnable = "#nullable enable";
    public const NamingConvention namingConvention = NamingConvention.SnakeCase;
    public const DatabaseProvider databaseProvider = DatabaseProvider.MySQL;
    public const string IdentifierField = "Id";
}